# Generated by Django 3.0.3 on 2020-02-25 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_contact', models.CharField(max_length=100)),
                ('user_late', models.CharField(max_length=100)),
                ('user_long', models.CharField(max_length=100)),
                ('user_village', models.CharField(max_length=100)),
                ('user_address', models.TextField()),
                ('user_teh', models.CharField(max_length=100)),
                ('user_dist', models.CharField(max_length=100)),
                ('user_state', models.CharField(max_length=100)),
                ('user_country', models.CharField(max_length=100)),
                ('user_state_id', models.CharField(max_length=100)),
                ('user_country_id', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
