# Generated by Django 3.0.3 on 2020-03-06 05:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sortname', models.CharField(max_length=100, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('phonecode', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en_name', models.CharField(max_length=100, null=True)),
                ('in_name', models.CharField(max_length=100, null=True)),
                ('mrt_name', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(default='default.jpg', upload_to='')),
                ('status', models.PositiveSmallIntegerField(default='0')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en_type', models.CharField(max_length=100, null=True)),
                ('in_type', models.CharField(max_length=100, null=True)),
                ('mrt_type', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(default='default.jpg', upload_to='')),
                ('status', models.PositiveSmallIntegerField(default='0')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animal.Group')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('code', models.CharField(max_length=100, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animal.Country')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_group', models.IntegerField(blank=True, null=True)),
                ('animal_breed', models.IntegerField(blank=True, null=True)),
                ('animal_milk', models.IntegerField(blank=True, null=True)),
                ('animal_color', models.CharField(blank=True, max_length=100, null=True)),
                ('animal_age', models.CharField(blank=True, max_length=100, null=True)),
                ('animal_weight', models.CharField(blank=True, max_length=100, null=True)),
                ('animal_child', models.CharField(blank=True, max_length=100, null=True)),
                ('animal_info', models.CharField(blank=True, max_length=100, null=True)),
                ('animal_price', models.CharField(blank=True, max_length=100, null=True)),
                ('front_image', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='animal_pics')),
                ('back_image', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='animal_pics')),
                ('left_image', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='animal_pics')),
                ('right_image', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='animal_pics')),
                ('approved_status', models.PositiveSmallIntegerField(default='0')),
                ('delete_status', models.PositiveSmallIntegerField(default='0')),
                ('sold_status', models.PositiveSmallIntegerField(default='0')),
                ('user_name', models.CharField(blank=True, max_length=100, null=True)),
                ('user_contact', models.CharField(blank=True, max_length=100, null=True)),
                ('user_late', models.CharField(blank=True, max_length=100, null=True)),
                ('user_long', models.CharField(blank=True, max_length=100, null=True)),
                ('user_village', models.CharField(blank=True, max_length=100, null=True)),
                ('user_address', models.TextField(blank=True, null=True)),
                ('user_teh', models.CharField(blank=True, max_length=100, null=True)),
                ('user_dist', models.CharField(blank=True, max_length=100, null=True)),
                ('user_state', models.CharField(blank=True, max_length=100, null=True)),
                ('user_country', models.CharField(blank=True, max_length=100, null=True)),
                ('user_state_id', models.IntegerField(blank=True, null=True)),
                ('user_country_id', models.IntegerField(blank=True, null=True)),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LikeUnlike',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('like_unlike', models.PositiveSmallIntegerField(default='0')),
                ('time', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animal.Post')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('user_contact', models.CharField(blank=True, max_length=100, null=True)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('comment_status', models.PositiveSmallIntegerField(default='0')),
                ('time', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('dlt_status', models.PositiveSmallIntegerField(default='0')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animal.Post')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
