# Generated by Django 3.0.3 on 2020-02-26 07:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en_name', models.CharField(max_length=100, null=True)),
                ('in_name', models.CharField(max_length=100, null=True)),
                ('mrt_name', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(default='default.jpg', upload_to='')),
                ('status', models.PositiveSmallIntegerField(default='0')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en_type', models.CharField(max_length=100, null=True)),
                ('in_type', models.CharField(max_length=100, null=True)),
                ('mrt_type', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(default='default.jpg', upload_to='')),
                ('status', models.PositiveSmallIntegerField(default='0')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animal.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_group', models.IntegerField()),
                ('animal_bread', models.IntegerField()),
                ('animal_milk', models.IntegerField()),
                ('animal_color', models.CharField(max_length=100, null=True)),
                ('animal_age', models.TextField(null=True)),
                ('animal_weight', models.CharField(max_length=100, null=True)),
                ('animal_child', models.IntegerField(null=True)),
                ('animal_info', models.CharField(max_length=100, null=True)),
                ('animal_price', models.CharField(max_length=100, null=True)),
                ('front_image', models.ImageField(default='default.jpg', upload_to='animal_pics')),
                ('back_image', models.ImageField(default='default.jpg', upload_to='animal_pics')),
                ('left_image', models.ImageField(default='default.jpg', upload_to='animal_pics')),
                ('right_image', models.ImageField(default='default.jpg', upload_to='animal_pics')),
                ('approved_status', models.PositiveSmallIntegerField(default='0')),
                ('delete_status', models.PositiveSmallIntegerField(default='0')),
                ('sold_status', models.PositiveSmallIntegerField(default='0')),
                ('user_name', models.CharField(max_length=100, null=True)),
                ('user_contact', models.CharField(max_length=100, null=True)),
                ('user_late', models.CharField(max_length=100, null=True)),
                ('user_long', models.CharField(max_length=100, null=True)),
                ('user_village', models.CharField(max_length=100, null=True)),
                ('user_address', models.TextField(null=True)),
                ('user_teh', models.CharField(max_length=100, null=True)),
                ('user_dist', models.CharField(max_length=100, null=True)),
                ('user_state', models.CharField(max_length=100, null=True)),
                ('user_country', models.CharField(max_length=100, null=True)),
                ('user_state_id', models.IntegerField(null=True)),
                ('user_country_id', models.IntegerField(null=True)),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
