# Generated by Django 3.0.3 on 2020-02-27 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0002_country_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='animal_bread',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='animal_group',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='animal_milk',
            field=models.IntegerField(null=True),
        ),
    ]
