# Generated by Django 3.0.3 on 2020-02-27 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0004_auto_20200227_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='back_image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='animal_pics'),
        ),
        migrations.AlterField(
            model_name='post',
            name='front_image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='animal_pics'),
        ),
        migrations.AlterField(
            model_name='post',
            name='left_image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='animal_pics'),
        ),
        migrations.AlterField(
            model_name='post',
            name='right_image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='animal_pics'),
        ),
    ]
