# Generated by Django 3.0.3 on 2020-02-27 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0005_auto_20200227_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='animal_age',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='animal_child',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
