# Generated by Django 3.0.3 on 2020-02-28 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0006_auto_20200227_1422'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='animal_bread',
            new_name='animal_breed',
        ),
    ]
