# Generated by Django 3.0.3 on 2020-02-29 10:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0008_likeunlike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likeunlike',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 2, 29, 10, 58, 44, 47920)),
        ),
    ]
