# Generated by Django 3.0.3 on 2020-02-29 11:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0009_auto_20200229_1058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likeunlike',
            old_name='animal_id',
            new_name='animal',
        ),
        migrations.AlterField(
            model_name='likeunlike',
            name='time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
