# Generated by Django 3.0.3 on 2020-03-03 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0012_comments_user_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likeunlike',
            old_name='author',
            new_name='author_like',
        ),
    ]
