# Generated by Django 3.0.3 on 2020-03-03 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0013_auto_20200303_0852'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likeunlike',
            old_name='animal',
            new_name='animal_like',
        ),
    ]
