# Generated by Django 3.0.3 on 2020-03-03 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0014_auto_20200303_0907'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likeunlike',
            old_name='animal_like',
            new_name='animal',
        ),
        migrations.RenameField(
            model_name='likeunlike',
            old_name='author_like',
            new_name='author',
        ),
    ]
